### ISSUE TITLE
Feature request: Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [aufzayed/bugbounty#6]
Hello, your repository is currently missing the Code of Conduct. If you want to add this, then I can submit a PR. In that case, I need a contact address (email address) that will get enlisted in the Code of Conduct file. Please let me know what you think about that.

Thanks!

**Comment by aufzayed** [comment]
sorry for the late response, is it important to add a code of conduct file to my repo? why?

**Comment by FahimFBA** [comment]
A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community.

**Comment by aufzayed** [comment]
ok, you can add "aufzayed@gmail.com"
